### ISSUE TITLE
This solution doesn't work if android:TabbedPage.ToolbarPlacement="Bottom"

### ISSUE THREAD

**Issue by tbaggett** [david-js/XFTabReselect#1]
Thanks for your effort on this solution. 

While it works as described when using the default Android tab bar at the top of the page, it doesn't work if the tab bar is placed at the bottom of the page.

I added the following lines to the MainPage.xaml file as suggested in https://montemagno.com/xamarin-forms-official-bottom-navigation-bottom-tabs-on-android/:
```
xmlns:android="clr-namespace:Xamarin.Forms.PlatformConfiguration.AndroidSpecific;assembly=Xamarin.Forms.Core"
android:TabbedPage.ToolbarPlacement="Bottom"

```

**Comment by lestersconyers** [comment]
PR #2 should fix this issue

**Comment by david-js** [comment]
The PR has been merged and verified to work.
